
apple_bundle(
  name = 'DemoExtension',
  binary = ':DemoExtensionLibrary#shared',
  extension = 'appex',
  info_plist = 'Info.plist',
  visibility = ['PUBLIC'],
)

apple_library(
  name = 'DemoExtensionLibrary',
  preprocessor_flags = ['-fobjc-arc'],
  headers = glob([
    '*.h',
  ]),
  srcs = glob([
    '*.m',
  ]),
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
   ],
)
